"""Regenerate ~/fillers (40 clips) and ~/fillers_bail (4 notices) in the LIVE
TTS voice — gpt-4o-mini-tts + Filipino-accent instructions (2026-08-12 accent
work) — replacing the old tts-1/echo clips so pre-recorded audio matches the
streamed answers.

Reuses voice_io.tts_create_kwargs() from the -main checkout so the clips are
generated by the exact same code path (instructions + pronunciation hints) as
live speech. Bail texts are recovered by transcribing the existing wavs.

Run in the app venv:
  ~/Supervaise-Reachy-Mini-Project-main/app/.venv/bin/python ~/gen_voice_wavs_accent.py

Stages into *.new dirs, backs up the old dirs, then swaps — safe while the
service runs (aplay opens files per-utterance).
"""
import os, shutil, subprocess, sys, time

APP = os.path.expanduser("~/Supervaise-Reachy-Mini-Project-main/app")
sys.path.insert(0, APP)

# Match the live systemd drop-in (wakeword.conf) — voice_io reads these at import.
os.environ.setdefault("OPENAI_TTS_MODEL", "gpt-4o-mini-tts")
os.environ.setdefault(
    "OPENAI_TTS_INSTRUCTIONS",
    "You are an elderly Filipino statesman in his late eighties, a retired "
    "Chief Justice of the Philippines. Speak English with a natural Filipino "
    "(Tagalog-influenced) accent. Warm, dignified, measured and deliberate "
    "pace, formal courtroom diction. Pronounce Filipino words, names, and "
    "places with native Tagalog pronunciation.",
)
from dotenv import load_dotenv
load_dotenv(os.path.join(APP, ".env"))
import voice_io
from voice_io import _sync_client, tts_create_kwargs, TTS_MODEL_DEFAULT, TTS_VOICE_DEFAULT, TTS_SPEED_DEFAULT

FILLER_TEXTS = [
    "Ah — a fine question. Allow me a moment to consult what my record holds.",
    "Yes; let me give that the consideration it deserves — a moment, if you please.",
    "A thoughtful question. Permit me to gather my recollections properly.",
    "Let me reflect on that for a moment; a proper answer deserves a proper pause.",
    "Hmm — allow me to draw the threads together before I speak.",
    "Well now, that is worth answering with care. Bear with me a moment.",
    "I should like to answer this properly, so let me consult my record first.",
    "A moment, if you would — I prefer to weigh my words before I offer them.",
    "Let me think this through as it deserves; I shall be with you shortly.",
    "Ah — give me just a moment to marshal my thoughts on this.",
    "Ah, yes. Let me look back through my years on the bench for this one.",
    "One moment po — I want to give you an answer worthy of the question.",
    "Hmm. There is something in my record that speaks to this; let me recall it properly.",
    "Patience, my friend — good judgment is never rushed.",
    "Let me search my memory; fifty years of law leaves many pages to turn.",
    "A moment po. Even on the Court, I never answered without reflection.",
    "That touches something I have written about; allow me to find the thread.",
    "Give me a breath to set my thoughts in order.",
    "Ah — I have opinions on this, in both senses of the word. One moment.",
    "Let me weigh this as I would have weighed a case — carefully.",
    "Hmm, a question after my own heart. Bear with me briefly.",
    "I am gathering my recollections — the archive of an old jurist is vast.",
    "Steady now — the right words are worth a short wait.",
    "Yes, I recall something on this. Let me bring it into focus.",
    "Allow an old Chief Justice a moment of deliberation.",
    "The law taught me never to speak before thinking. A moment, please.",
    "Let me consult the record of my years — it rarely fails me.",
    "Ah, this deserves more than a quick reply. Give me a moment po.",
    "I shall answer presently — deliberation first, pronouncement after.",
    "Hold on briefly — I want to be precise, as a judge must be.",
    "Hmm — let me turn this over once or twice before I speak.",
    "There is wisdom in the pause; allow me mine.",
    "A fine point. I am drawing on many years to answer it well.",
    "Sandali lamang po — a careful answer is a kind answer.",
    "Let me marshal the relevant memories; they are many.",
    "Ah, you test my recollection — pleasantly so. One moment.",
    "Every good ruling begins with quiet thought. Grant me a little.",
    "I am consulting my own precedents, so to speak.",
    "Bear with me po; I would rather be right than quick.",
    "Yes — I know just where to look for this. A brief moment.",
]

FILLER_DIR = os.path.expanduser("~/fillers")
BAIL_DIR = os.path.expanduser("~/fillers_bail")
BAIL_FILES = ["please_be_specific.wav", "not_connected.wav", "enroll_prompt.wav", "enroll_done.wav"]
STAMP = time.strftime("%Y%m%d")

client = _sync_client()
print(f"engine: {TTS_MODEL_DEFAULT} voice={TTS_VOICE_DEFAULT} instructions={'yes' if voice_io.TTS_INSTRUCTIONS_DEFAULT else 'NO'}")


def transcribe(path):
    with open(path, "rb") as f:
        return client.audio.transcriptions.create(model="whisper-1", file=f, language="en").text.strip()


def synth_wav(text, wav_path, rate=None):
    kw = tts_create_kwargs(TTS_MODEL_DEFAULT, TTS_VOICE_DEFAULT, TTS_SPEED_DEFAULT, text)
    mp3 = wav_path + ".mp3"
    with open(mp3, "wb") as f:
        f.write(client.audio.speech.create(**kw).content)
    cmd = ["ffmpeg", "-y", "-loglevel", "quiet", "-i", mp3]
    if rate:
        cmd += ["-ar", str(rate), "-ac", "1"]
    subprocess.run(cmd + [wav_path], check=True)
    os.unlink(mp3)


# --- recover bail texts from the existing wavs ---
bail_texts = {}
for name in BAIL_FILES:
    src = os.path.join(BAIL_DIR, name)
    bail_texts[name] = transcribe(src)  # NOTE: enroll_prompt garbles via whisper; correct text is "Enrolling your voice. After the beep, please speak naturally for about ten seconds."
    print(f"[text] {name}: {bail_texts[name]}")

# --- stage new clips ---
for d in (FILLER_DIR + ".new", BAIL_DIR + ".new"):
    shutil.rmtree(d, ignore_errors=True)
    os.makedirs(d)

for i, text in enumerate(FILLER_TEXTS, 1):
    synth_wav(text, f"{FILLER_DIR}.new/{i:02d}.wav")  # 24 kHz like the old pool
    print(f"  filler {i:02d} ok")

for name in BAIL_FILES:
    synth_wav(bail_texts[name], f"{BAIL_DIR}.new/{name}", rate=16000)  # old bail wavs are 16 kHz mono
    print(f"  bail {name} ok")

# --- swap in (old pools kept as .bak) ---
for live in (FILLER_DIR, BAIL_DIR):
    bak = f"{live}.bak-tts1-{STAMP}"
    shutil.rmtree(bak, ignore_errors=True)
    os.rename(live, bak)
    os.rename(live + ".new", live)
    print(f"[swap] {live}  (old -> {bak})")
print("done")
