"""CE-9 human-authored specification of the recommended dimensions (bottom-up level m=20 of the whole-corpus Ward tree).
Keyed by cluster number in cache/ce9_level_m20.npy. Each entry is checked against the cluster's size (`n`) so a changed partition cannot silently
mislabel a dimension. Names and definitions are written from the cluster profiles (top TF-IDF terms, curated keywords, entities, exemplars, and the FINE
partition's sub-clusters) and describe the SUBJECT in one or two sentences; none lists members.  tier / theme_anchor / doc counts are computed, not written here.
Id policy: a dimension that is the same subject as a v1 topic KEEPS that v1 id (downstream references stay valid); everything else gets a new id."""

SPEC = {
    1:  dict(n=148, id="life_story_family_school_and_church", name="Life Story: Family, School and Church",
             definition="The Chief Justice's own life: his family, his schooling and mentors, his church and community life, and the eulogies and tributes he gives to people who shaped him."),
    2:  dict(n=94, id="criminal_trials_and_prosecutions", name="Criminal Trials, Prosecutions and the ICC",
             definition="How major criminal cases actually proceed in the Philippines: bail, probable cause, the Sandiganbayan and the plunder and pork-barrel trials, and the International Criminal Court's case against Duterte."),
    3:  dict(n=64, id="international_law_disputes", name="International Law: the West Philippine Sea and Arbitration",
             definition="The Philippines' sea dispute with China: the 2016 arbitral award, UNCLOS, the exclusive economic zone and the nine-dash line, and what international arbitration can and cannot enforce."),
    4:  dict(n=62, id="property_contracts_and_economic_rights", name="Property, Contracts and Labor Rights",
             definition="Supreme Court decisions on ownership, contracts, natural resources, investment and labor, read for what they mean for livelihoods and business."),
    5:  dict(n=59, id="how_the_supreme_court_decides", name="How the Supreme Court Decides",
             definition="How the Court reasons and writes its decisions, and why the judiciary's independence from the other branches matters."),
    6:  dict(n=56, id="libel_and_cybercrime", name="Libel and Cybercrime",
             definition="Criminal libel and cybercrime cases: the Maria Ressa cyberlibel prosecution, libel of public figures online, and the Cybercrime Prevention Act."),
    7:  dict(n=53, id="presidential_power_martial_law_people_power", name="Presidential Power, Martial Law and People Power",
             definition="The limits of presidential power in a crisis: martial law and rebellion, EDSA and the presidencies of Estrada and Arroyo."),
    8:  dict(n=48, id="elections_and_automated_voting", name="Elections and Automated Voting",
             definition="How Philippine elections are run and litigated: the Commission on Elections, precinct-count optical scanners and the disputes over automation."),
    9:  dict(n=43, id="judiciary_milestones_and_tributes", name="The Judiciary's Milestones and Tributes",
             definition="Celebrations of the judiciary and of the people in it: the Supreme Court centenary, retirements, book launches, honors and tributes to fellow justices."),
    10: dict(n=42, id="judicial_reform", name="Judicial Reform and Court Delay",
             definition="Reforming the courts: the Action Program for Judicial Reform, case backlogs, judges' pay and how to speed up justice."),
    11: dict(n=40, id="party_list_charter_change_and_dynasties", name="Party-List, Charter Change and Political Dynasties",
             definition="How Congress is chosen and the Constitution is amended: the party-list system, Charter change and political dynasties."),
    12: dict(n=39, id="science_technology_and_the_law", name="Science, Technology and the Law",
             definition="How courts and lawyers should deal with new science: DNA and genetics, cloning, the internet and artificial intelligence."),
    13: dict(n=36, id="economy_taxes_and_prosperity", name="The Economy, Taxes and Wages",
             definition="Economic policy seen through a lawyer's eyes: growth, jobs, taxes and wages, and what makes nations prosper."),
    14: dict(n=35, id="impeachment_accountability", name="Impeachment",
             definition="The impeachment process from the House to the Senate: its rules and limits, and the Corona and Sara Duterte cases."),
    15: dict(n=57, id="foundation_for_liberty_and_prosperity", name="The Foundation for Liberty and Prosperity and Its Benefactors",
             definition="The Foundation's work and people: scholarships and dissertation fellows, its museum and Prosperity Fund, and the business leaders and donors who fund it."),
    16: dict(n=32, id="public_funds_budget_and_bank_evidence", name="Public Funds, the Budget and Bank Evidence",
             definition="How public money is spent and traced: the budget, the DAP and PDAF rulings, and bank deposits used as evidence of corruption."),
    17: dict(n=29, id="us_supreme_court_and_american_politics", name="The US Supreme Court and American Politics",
             definition="Commentary on the American presidency and the US Supreme Court, from Trump to Biden and the electoral college, and what they teach the Philippines."),
    18: dict(n=27, id="independent_commissions_and_appointments", name="Independent Commissions and Appointments",
             definition="The constitutional commissions and the Ombudsman: how their officials are appointed, how long they serve and how independent they really are."),
    19: dict(n=27, id="twin_beacons_doctrine", name="Liberty and Prosperity: the Twin Beacons",
             definition="The Chief Justice's core philosophy that liberty and prosperity depend on each other, and that both rest on the rule of law and social justice."),
    20: dict(n=26, id="marcos_robredo_election_contest", name="The Marcos-Robredo Election Contest",
             definition="The vice-presidential protest of 2016 and the 2022 campaign that followed: canvassing, protests and what the results meant."),
    21: dict(n=26, id="bangsamoro_peace_process", name="The Bangsamoro Peace Process",
             definition="The peace agreements with the MILF, the Bangsamoro Basic Law and the question of whether they fit the Constitution."),
    22: dict(n=26, id="supreme_court_vacancies_and_chief_justiceship", name="Supreme Court Vacancies and the Chief Justiceship",
             definition="Who sits on the Court and who leads it: retirements, appointments by President Duterte and the succession to the chief justiceship."),
    23: dict(n=26, id="faith_journey", name="Faith: Scripture, Prayer and the Gospel",
             definition="Reflections on scripture and prayer, on Jesus and the Gospel and on the Bukas Loob sa Diyos community, drawn mainly from the faith-themed books."),
    25: dict(n=24, id="asean_law_association", name="The ASEAN Law Association",
             definition="The regional association of lawyers and judges the Chief Justice helped lead, and the rule of law in Southeast Asia."),
    27: dict(n=23, id="ill_gotten_wealth_and_the_pcgg", name="Ill-Gotten Wealth and the PCGG",
             definition="The recovery of wealth amassed under Marcos: sequestration, forfeiture and the Sandiganbayan's rulings."),
    28: dict(n=21, id="citizenship_and_residency_grace_poe", name="Citizenship and Residency: the Grace Poe Case",
             definition="Who counts as a natural-born citizen (foundlings, dual citizens and residency), argued through the Grace Poe case."),
    29: dict(n=21, id="marriage_annulment_and_the_family_code", name="Marriage, Annulment and the Family Code",
             definition="How the law treats marriage: psychological incapacity, nullity, divorce and the Family Code."),
    30: dict(n=21, id="bar_exam_and_legal_education", name="The Bar Exam and Legal Education",
             definition="How lawyers are trained and admitted: the bar examinations, legal education and the profession's duties."),
    33: dict(n=20, id="jbc_discernment_and_appointment", name="The Judicial and Bar Council",
             definition="How judges are nominated: the Council's role, its rules and the shortlist for each vacancy."),
}

# Clusters of the recommended-level partition that are NOT proposed as dimensions, with the measurement that stopped each one (cache/ce9_readable_m20.json, ce9_pairs runs).
UNBUILT = {
    24: dict(n=24, name="Business Leaders and Philanthropy", why="MERGED into the Foundation dimension: on deployed centroids it is 0.74-0.78 of it whatever its matcher (the donors ARE the business leaders); partition centroids 0.58."),
    26: dict(n=23, name="Public Officials' Duties and Data Privacy", why="NOT PROPOSED, matcher unfinished: the best readable term set catches 6 of its 23 documents (no term reaches 0.5 precision at df >= 5; 'privacy' catches 48 documents, 8 of them inside)."),
    31: dict(n=21, name="The Chief Justiceship and a Judicial Career", why="NOT PROPOSED, matcher unfinished: no readable term catches even 30% of its own documents (best: 'art's' 34 docs / 10 inside; 'davide standard' 16 / 4); a union of every promising term catches 570+ documents. Real in embedding space (10 biography chapters), invisible to metadata."),
    32: dict(n=21, name="Corporate Governance and Integrity", why="NOT PROPOSED, matcher unfinished: best readable set catches 4 of 21 documents; 'corporate governance' (16 docs, 7 inside), 'independent directors' (7, 4) and 'governance' (125 docs, 15 inside) are the only handles."),
}
